//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdCurrency { get; set; }
        public int IdCreditProduct { get; set; }
        public decimal Debt { get; set; }
        public decimal DebtRate { get; set; }
        public bool IsActive { get; set; }
        public decimal MonthlyPayment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual CreditProduct CreditProduct { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
