//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitСard
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public decimal Balance { get; set; }
        public int idProduct { get; set; }
        public string Number { get; set; }
        public string OwnerName { get; set; }
        public System.DateTime ValidTHRU { get; set; }
        public int IdPaymentSystem { get; set; }
        public int IdCurrency { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DebtCardProduct DebtCardProduct { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
    }
}
