//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdCurrency { get; set; }
        public int IdDepositProduct { get; set; }
        public decimal Deposit1 { get; set; }
        public decimal DepositRate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ValidTHRU { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DepositProduct DepositProduct { get; set; }
    }
}
