//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomDBEntities : DbContext
    {
        public DiplomDBEntities()
            : base("name=DiplomDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<CreditCard> CreditCard { get; set; }
        public virtual DbSet<CreditCardProduct> CreditCardProduct { get; set; }
        public virtual DbSet<CreditProduct> CreditProduct { get; set; }
        public virtual DbSet<CreditType> CreditType { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DebitСard> DebitСard { get; set; }
        public virtual DbSet<DebtCardProduct> DebtCardProduct { get; set; }
        public virtual DbSet<Deposit> Deposit { get; set; }
        public virtual DbSet<DepositProduct> DepositProduct { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<PaymentSystem> PaymentSystem { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
